### PR TITLE
[Update][WIP] 1.20.2

### PR DESCRIPTION
**Pull request by Xernium**
# Progress tracker for 1.20.2
This pull-request is meant to track and implement the changes leading up to the 1.20.2 release.   
Usually we achieve this by adding compatibility for snapshots of the release version in development.
Certain steps along the way may be skipped or broken.
## Warning: Work-in-progress
During the Mojang development cycle, changes in the latest snapshots may be mirrored here
Due to the nature of the development releases, there is absolutely no support provided, for this reason:

**DO NOT USE THIS CODE IN PRODUCTION. NONE OF THE CHANGES HERE ARE FINAL UNTIL MERGED**
 
If you have any issues to report/ want to contribute fixes:
- Contact us on the PaperMC Discord in the velocity-dev channel
- Comment with links and information on this pull-request
- Create issues or pull-requests on the origin repository of this update

Feel free to also contact us with technical questions or design concerns

### CODE REVIEW

**Comment by Xernium** [comment]
# Snapshot 23w31a
- New protocol phase (CONFIG)    

**I am aware of the mistakes I made during renaming something. This will be fixed in the next commit**
Not fully implemented as of 03-08-2023

**Comment by Potothingi** [comment]
https://www.minecraft.net/en-us/article/minecraft-1-20-2-release-candidate-1
1.20.2 is coming soon.

**Comment by Potothingi** [comment]
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-20-2
1.20.2 is now available.

**Comment by Potothingi** [comment]
Is this PR progressing?
Or can someone edit this PR?

**Comment by Nacioszeczek** [comment]
We're aware 1.20.2 is out.
Updates to Paper and Velocity as always have no ETA, please wait patiently for the release and feel free to join our [Discord](https://discord.gg/papermc) so you can follow any updates as soon as possible.

**Comment by Phoenix616** [comment]
What's the plan regarding exposing the configuration phase? (E.g. in API and especially on server switches) Or at least preventing that packets that aren't configuration phase ones are sent by plugins/backend servers during the configuration phase on login/server switch?

**Comment by Xernium** [comment]
Superseded by #1088

**Pull request closed without merging**
