### PR TITLE
feat: expose list order in TabListEntry

### LINKED ISSUE #1450: Make list order int exposed in TabListEntry builder
### Requested Feature

1.21.3 finally adds order to tab lists, this is a huge deal for people who have been using hacky teams for ordering, support for this in velocity would be cool. I see it already is implemented on the packet level but currently I don't believe you can use tablistentry builder for it yet

### Why is this needed?

Ordering players on tab in a more graceful manner.

### Alternative Solutions

using velocity internals and editing packets?

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Timongcraft**
Exposes the tab list ordering introduced in 1.21.2.

Fixes: https://github.com/PaperMC/Velocity/issues/1450

### CODE REVIEW

**Comment by NEZNAMY** [comment]
Is there any kind of check preventing the action from being sent to <1.21.2 clients? Same for addEntry.

**Comment by Timongcraft** [comment]
No, I just assumed it would be like listed, but I only now noticed, because of you, that that is indeed not newer than the VelocityTabList.

**Comment by NEZNAMY** [comment]
You forgot to (conditionally) add the action somewhere here:
https://github.com/Timongcraft/Velocity/blob/feat/tablist-ordering/proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabList.java#L146

**Comment by Timongcraft** [comment]
Oh, yeah, thanks!

**Review by electronicboy — APPROVED** [review]

**Review by RealBauHD — APPROVED** [review]

**Review by 4drian3d — APPROVED** [review]

**Pull request merged**
