### PR TITLE
Bump adventure to 4.18.0

### PR DESCRIPTION
**Pull request by RealBauHD**

### CODE REVIEW

**Comment by electronicboy** [comment]
This requires more than just a simple version bump

**Comment by RealBauHD** [comment]
I went through the changes from adventure and didn't notice anything that needed attention.
Or have I overlooked something in the VirtualComponents?
4.16.0 and 4.17.0 were also just simple bumps.

**Comment by electronicboy** [comment]
The shadow component field needs integrating into our component nbt
serialiser

**Comment by RealBauHD** [comment]
Oh you're right, I look into that

**Comment by RealBauHD** [comment]
It already works
because the serializer translates the gson types and not the components

**Review by electronicboy — APPROVED** [review]
I'd forgotten that we'd gone that route in the interim

**Pull request merged**
