### PR TITLE
Modern Forge Support

### PR DESCRIPTION
**Pull request by danorris709**
## What does this do?
This adds the proxy side implementation of the [Forge Client Reset Packet](https://github.com/Just-Chaldea/Forge-Client-Reset-Packet) mod and as such allows modded clients using Forge versions of 1.13+ to use proxies. 

This is achieved by sending the "client reset packet" to the Forge client before they swap servers which resets the client's registries before allowing them to enter the server. This is important as in 1.13 Mojang's codebase changed and the registries were introduced for datapacks. This means that whilst for Vanilla clients you can assume the registry will match between the client and the server, you cannot do that for the modded client as the server and client may not have matching mods (or any number of other similar issues). Hence, the reset packet is required to reset (and sync) the registries with the server before allowing the client to join the server seemlessly.

It is also important to note that this does not break existing Vanilla compatibility either.

## Why is this needed?
This is needed as the current solution is the distribution of a fork of Velocity and adding the Forge Client Reset Packet mod to the mod's modpack. Whilst this works for the time being it has resulted in mass confusion, plenty of people not knowing where to go for support, as well as general misinformation spread (mostly accidentally by those unaware such a mod exists). Therefore, adding official support is the best route as it will allow the communities that need this to grow again and reduce the bar for entry.

## What's changed from last time?
[Last time](https://github.com/PaperMC/Velocity/pull/690) there was no active implementation and there was a lot of theories as to if the solution would even work. However, now this mod has been in use for almost a year and is used daily by thousands of players on huge networks in, and out, of the Pixelmon community. 

## Forge PR
https://github.com/MinecraftForge/MinecraftForge/pull/9313

## Issue
https://github.com/PaperMC/Velocity/issues/248

## Links
https://www.curseforge.com/minecraft/mc-mods/forge-client-reset-packet
https://github.com/Just-Chaldea/Forge-Client-Reset-Packet

## Example servers
- `hub.mc-complex.com` (Vanilla servers & Pixelmon servers)
- `play.nebulamc.gg`
- `play.mc-blaze.com` (Vanilla servers & Pixelmon servers)
- `mc.pokesmash.co`
- `play.happycloudmc.com`
- `pixelmon.projectshiba.com`
- `hexagonmc.eu` (Vanilla servers & Pixelmon servers)
- `roanoke.network` (Vanilla servers & Pixelmon servers)
- `play.squirtlesquadmc.com`  (Vanilla servers & Pixelmon servers)

### CODE REVIEW

**Comment by Mikirae** [comment]
This would greatly benefit the modded communities that require hubs. Allowing clients to have a reset packet means that they no longer get stuck on the "Negotiating" screen should something go wrong, and would greatly enhance the user experience on networks.

**Comment by JT122406** [comment]
@danorris709 Is this finished and working?
Also can you merge in velocity main into it

**Comment by Rasgnarok** [comment]
> @danorris709 Is this finished and working? Also can you merge in velocity main into it

Worth reading the PR before asking questions, it's clearly explained.

**Comment by JT122406** [comment]
> > @danorris709 Is this finished and working? Also can you merge in velocity main into it
> 
> Worth reading the PR before asking questions, it's clearly explained.

I Did read the PR but there has been a lot of commits then none for 2 weeks so I was asking to make sure

**Comment by Rasgnarok** [comment]
> > > @danorris709 Is this finished and working? Also can you merge in velocity main into it
> > 
> > 
> > Worth reading the PR before asking questions, it's clearly explained.
> 
> I Did read the PR but there has been a lot of commits then none for 2 weeks so I was asking to make sure

No, I meant read the description. The PR doesn't need commits every day to be usable, in-use, working or finished.

**Comment by UnperishedFoods** [comment]
@danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)

**Comment by danorris709** [comment]
> @danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)

So I believe the implementation of it working with modern forwarding is something you'd need to do on your server software, and hasn't really got anything to do with the Velocity modifications. I know that with the Arclight changes I've made in 1.16.5 it only supports legacy forwarding but that's not as a result of any changes made here and only because I've not added support for any other forwarding mode on the Arclight side. I hope that answers your question, if not you're welcome to DM me on Discord :)

**Comment by adde0109** [comment]
> @danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)

You could try:
https://github.com/adde0109/Proxy-Compatible-Forge

**Comment by UnperishedDev** [comment]
Yes, I got it to work with Ambassador and Proxy Compatible Forge on 1.16.5 with FCRP (Forge Client Reset Packet). Is there any plan for FCRP to be updated past 1.16.5 (just so the minor inconvenience of disconnecting and reconnecting with ambassador could be avoided)? I saw under the Issues tab for FCRP that "other versions are in the works" back in January but that seemed to be it. Do you (@danorris709) happen to have insight on that? Thanks so much for your help! It's greatly appreciated.

**Comment by UnperishedDev** [comment]
Yes, I got it to work with Ambassador and Proxy Compatible Forge on 1.16.5 with FCRP (Forge Client Reset Packet). Is there any plan for FCRP to be updated past 1.16.5 (just so the minor inconvenience of disconnecting and reconnecting with ambassador could be avoided)? I saw under the Issues tab for FCRP that "other versions are in the works" back in January but that seemed to be it. Do you (@danorris709) happen to have insight on that? Thanks so much for your help! It's greatly appreciated.

**Comment by UnperishedFoods** [comment]
> @danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)

Yes, I got it to work with Ambassador and Proxy Compatible Forge on 1.16.5 with FCRP (Forge Client Reset Packet). Is there any plan for FCRP to be updated past 1.16.5 (just so the minor inconvenience of disconnecting and reconnecting with ambassador could be avoided)? I saw under the Issues tab for FCRP that "other versions are in the works" back in January but that seemed to be it. Do you (@danorris709) happen to have insight on that? Thanks so much for your help! It's greatly appreciated.

**Comment by adde0109** [comment]
> > @danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)
> 
> Yes, I got it to work with Ambassador and Proxy Compatible Forge on 1.16.5 with FCRP (Forge Client Reset Packet). Is there any plan for FCRP to be updated past 1.16.5 (just so the minor inconvenience of disconnecting and reconnecting with ambassador could be avoided)? I saw under the Issues tab for FCRP that "other versions are in the works" back in January but that seemed to be it. Do you (@danorris709) happen to have insight on that? Thanks so much for your help! It's greatly appreciated.

I happen to have a fork on my GitHub profile that has a 1.18.2 and 1.19.2 version, but you will have to build them yourself.

**Comment by UnperishedFoods** [comment]
> > > @danorris709 How is it possible to implement this with modern velocity forwarding? I have a proxy network that I’d like to add modern forge (1.19.2) support to in the future. I need the fork of velocity, forge client reset packet, but how to accept IP forwarding backend server-side? Or is that not something that has been implemented yet? Sorry I’m not sure if I’m asking this in the right place but still :)
> > 
> > 
> > Yes, I got it to work with Ambassador and Proxy Compatible Forge on 1.16.5 with FCRP (Forge Client Reset Packet). Is there any plan for FCRP to be updated past 1.16.5 (just so the minor inconvenience of disconnecting and reconnecting with ambassador could be avoided)? I saw under the Issues tab for FCRP that "other versions are in the works" back in January but that seemed to be it. Do you (@danorris709) happen to have insight on that? Thanks so much for your help! It's greatly appreciated.
> 
> I happen to have a fork on my GitHub profile that has a 1.18.2 and 1.19.2 version, but you will have to build them yourself.

Amazing, I'll be testing that.

**Comment by fratik** [comment]
There is an issue with this PR where it kind of breaks compatibility with things. As far as I understand from debugging (I don't have much knowledge about the Minecraft protocol and Velocity so correct me if I'm wrong) Velocity changes the connection state to `PLAY` before firing `LoginEvent`, `PostLoginEvent` and `PlayerChooseInitialServerEvent` (see [here](https://github.com/PaperMC/Velocity/pull/932/files#diff-4fcf68fbecb068f39bcb559068c984f4396d338da5edbef4a282e8537e1e27dcL175)). The current implementation of this PR changes the state after handling the `ServerLoginSuccess` packet (see [here](https://github.com/PaperMC/Velocity/pull/932/files#diff-361114447ba8df4da9f802c5c76e518bc16744fce13177edab58a0cd509ca76cR238)) which happens after those events.
Why is this an issue? If you have logic that needs to for example send chat messages in those events, you can't do that anymore. This should also throw an exception (because a chat message is an unknown packet in the `LOGIN` phase), but for some reason [that check was removed](https://github.com/PaperMC/Velocity/commit/9da95d606ba5f75fd141c9f11b053d32dd5ec48c#diff-56ea7f2b9379ef9993dd549d4970121ca16aa3fb089ece6db49d9b6a0f414a50L495-L500) and [rewritten to just be silently ignored](https://github.com/PaperMC/Velocity/commit/9da95d606ba5f75fd141c9f11b053d32dd5ec48c#diff-7256d39c59cf629bc6e099b0c8751d882e44d83c16606e524d832a9844beea3aR51-R53).

**Comment by adde0109** [comment]
> There is an issue with this PR where it kind of breaks compatibility with things. As far as I understand from debugging (I don't have much knowledge about the Minecraft protocol and Velocity so correct me if I'm wrong) Velocity changes the connection state to `PLAY` before firing `LoginEvent`, `PostLoginEvent` and `PlayerChooseInitialServerEvent` (see [here](https://github.com/PaperMC/Velocity/pull/932/files#diff-4fcf68fbecb068f39bcb559068c984f4396d338da5edbef4a282e8537e1e27dcL175)). The current implementation of this PR changes the state after handling the `ServerLoginSuccess` packet (see [here](https://github.com/PaperMC/Velocity/pull/932/files#diff-361114447ba8df4da9f802c5c76e518bc16744fce13177edab58a0cd509ca76cR238)) which happens after those events. Why is this an issue? If you have logic that needs to for example send chat messages in those events, you can't do that anymore. This should also throw an exception (because a chat message is an unknown packet in the `LOGIN` phase), but for some reason [that check was removed](https://github.com/PaperMC/Velocity/commit/9da95d606ba5f75fd141c9f11b053d32dd5ec48c#diff-56ea7f2b9379ef9993dd549d4970121ca16aa3fb089ece6db49d9b6a0f414a50L495-L500) and [rewritten to just be silently ignored](https://github.com/PaperMC/Velocity/commit/9da95d606ba5f75fd141c9f11b053d32dd5ec48c#diff-7256d39c59cf629bc6e099b0c8751d882e44d83c16606e524d832a9844beea3aR51-R53).

This can be solved by adding a queue for all the PLAY messages until the client is in the PLAY state.

**Pull request closed without merging**
