### PR TITLE
Set proxy to build with Java 11 compatibility

### PR DESCRIPTION
**Pull request by BBaoVanC**
Not sure if this is the correct way to do it, but I use Java 18 on my system and building Velocity results in the proxy jar not being compatible with Java 17.

### CODE REVIEW

**Comment by 4drian3d** [comment]
I don't think this change is so necessary, it would only affect custom builds, and in that case, everyone can modify Velocity as required

**Comment by BBaoVanC** [comment]
What do you mean by custom builds?

**Comment by 4drian3d** [comment]
I mean that if you clone the project directly or through a fork it will affect when compiling on your own, but for the official Velocity distribution it will not have any effect

**Comment by electronicboy** [comment]
to my understanding, one should set it through the toolchain, that way it can do other stuff like ensuring that pulled in stuff is compatible with 11 and that the final output supports 11

**Comment by BBaoVanC** [comment]
> to my understanding, one should set it through the toolchain, that way it can do other stuff like ensuring that pulled in stuff is compatible with 11 and that the final output supports 11

So do you mean that I should set my system's Java version instead when building? It's kind of annoying to do that, I feel like it makes the most sense for it to build properly automatically, instead of needing to be set properly in CI, or on your own system or whatever.

**Comment by electronicboy** [comment]
No, I mean using he gradle toolchain system, which basically properly sets the JVM release, etc, properly

**Comment by BBaoVanC** [comment]
Like this, in 8b87ca3e87bb5ac189c5170a904f02619572686f?

**Comment by electronicboy** [comment]
yes

**Comment by BBaoVanC** [comment]
I also see that in `api/build.gradle` and `native/build.gradle`, it uses `sourceCompatibility` and `targetCompatibility` to set the Java version. Should this be changed to Gradle `toolchain` as well?

**Comment by astei** [comment]
I went ahead and made this change as part of the conversion of Velocity to use Gradle's Kotlin DSL

**Pull request closed without merging**
