### PR TITLE
Fix tablist header and footer desync

### LINKED ISSUE #1101: Tablist header and footer are not reset when a player using client 1.20.1 or lower is kicked from the backend.
Tablist header and footer are not reset when a player using client 1.20.1 or lower is kicked from the backend.

### PR DESCRIPTION
**Pull request by VeVeVeVel**
Resolves #1101

### CODE REVIEW

**Comment by VeVeVeVel** [comment]
This happens because 'existingConnection' is null when the player is kicked from the backend.
If there is a better solution than this, please apply it.

**Review by electronicboy — APPROVED** [review]

**Comment by RealBauHD** [comment]
This pr causes the problem that the tablist of plugins that set it in the "PostLoginEvent" is immediately reset again.

**Comment by electronicboy** [comment]
PostLoginEvent was never a place that we'd expect anybody to try setting that stuff given that the client is not even in a state to recieve such data

**Comment by RealBauHD** [comment]
Oh yeah that's actually true, did it in an old plugin before the config phase was invented

**Pull request merged**
