### PR TITLE
Allow underscore in hostname

### PR DESCRIPTION
**Pull request by ohAleee**

### CODE REVIEW

**Comment by Xernium** [comment]
Only letters, digits and hyphens are allowed under [RFC1035](https://www.rfc-editor.org/rfc/rfc1035) in public domain names, thus this feature won’t be considered.

**Comment by ohAleee** [comment]
it is useful with docker...

**Comment by Xernium** [comment]
That doesn't change the fact that you're not only breaking api spec but also Java spec with this. Plus this opens up the possibility of resource abuse from the outside.

**Comment by clrxbl** [comment]
> it is useful with docker...

There are so many workarounds to this and it is unlikely to actually be useful with Docker, name your containers properly and avoid underscores.

**Pull request closed without merging**
