### PR TITLE
[ci skip] make 'runShadow' workingDir use the 'run' directory

### PR DESCRIPTION
**Pull request by powercasgamer**
good: 
jetbrains_client64_qv4zIOrpX0
bad: 
jetbrains_client64_sBozxa6QNQ

### CODE REVIEW

**Comment by electronicboy** [comment]
1) Long fabled todo list but didn't wanna break my env
2) I did wanna look at getting the console working inside of IJ, as it's annoying that it doesn't as the process just seems to cause weird freezing issues as-is when tryna shutdown

**Comment by electronicboy** [comment]
(on that note, the task I always use is literally just called run, never needed run shadow, but, if we hit one, we should hit both

**Comment by powercasgamer** [comment]
> (on that note, the task I always use is literally just called run, never needed run shadow, but, if we hit one, we should hit both

Afaik the `run` task doesn't even work?
WindowsTerminal_9QWDGW2jIg

**Comment by electronicboy** [comment]
it screams but it's running fine

**Comment by powercasgamer** [comment]
> (on that note, the task I always use is literally just called run, never needed run shadow, but, if we hit one, we should hit both

Done

**Review by electronicboy — APPROVED** [review]

**Pull request merged**
