### PR TITLE
Username can be 16 * 3 bytes

### PR DESCRIPTION
**Pull request by Outfluencer**
see my pr #843

### CODE REVIEW

**Comment by xIsm4** [comment]
> see my pr #843

You are right, but in some cases it could reach 16 * 4

**Comment by Outfluencer** [comment]
list cases please
and read the conversation of the old pullrequest

**Review by astei — APPROVED** [review]

**Comment by xism4** [comment]
> list cases please and read the conversation of the old pullrequest

Based on the UTF-8 documentation, encoded strings using Java can reach more than 3*#codepoints.

**Comment by hugmanrique** [comment]
Java uses a modified UTF-8 encoding, see https://github.com/PaperMC/Velocity/pull/843#discussion_r950690571 for previous discussion.

**Comment by xism4** [comment]
> Java uses a modified UTF-8 encoding, see [#843 (comment)](https://github.com/PaperMC/Velocity/pull/843#discussion_r950690571) for previous discussion.

I see, so if I didn't see it wrong. Mojang implemented it wrong or just the docs are wrong? What a curiosity

**Comment by Outfluencer** [comment]
> > Java uses a modified UTF-8 encoding, see [#843 (comment)](https://github.com/PaperMC/Velocity/pull/843#discussion_r950690571) for previous discussion.
> 
> I see, so if I didn't see it wrong. Mojang implemented it wrong or just the docs are wrong? What a curiosity

No both are right Java just have a custom impl of utf8 with 3 bytes just read the old conversation…

**Comment by xism4** [comment]
> > > Java uses a modified UTF-8 encoding, see [#843 (comment)](https://github.com/PaperMC/Velocity/pull/843#discussion_r950690571) for previous discussion.
> > 
> > 
> > I see, so if I didn't see it wrong. Mojang implemented it wrong or just the docs are wrong? What a curiosity
> 
> No both are right Java just have a custom impl of utf8 with 3 bytes just read the old conversation…

Thanks for clarifing it, i ported to Waterfall

**Pull request merged**
