### PR TITLE
First version

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by KoxSosen** [comment]
There is a certain thing that comes to my mind while reading thru these changes...💭

**Comment by Neeonn** [comment]
ah yes the !whatever.isPresent() >>> whatever.isEmpty() fix

**Comment by Titaniumtown** [comment]
Thank you for your contribution to the opensource community.

**Comment by PermisosDev** [comment]
> ah yes the !whatever.isPresent() >>> whatever.isEmpty() fix

if you have better fixes, make a pull request. don't come throwing shit.

**Pull request closed without merging**
