### PR TITLE
Fix implements in class ResponseResult

### PR DESCRIPTION
**Pull request by microwin7**
Fixed inheritance of interface on ResultedEvent.Result in ResponseResult class

### CODE REVIEW

**Comment by astei** [comment]
I'm concerned that this could be a breaking change. What issue does this fix?

**Comment by 4drian3d** [comment]
> I'm concerned that this could be a breaking change. What issue does this fix?

Currently there is always a compiler error because "Result" is not found among the imports of class
Screenshot_1
For some reason, when compiling the project, no errors appear and everything works normally

Replacing it with ResultedEvent.Result eliminates the error because the ResultedEvent class is imported in the class.

This is not a big change and will not break anything because if you look at javadocs https://jd.velocitypowered.com/3.0.0/com/velocitypowered/api/event/player/ServerLoginPluginMessageEvent.ResponseResult.html there you actually use the ResultedEvent.Result
Screenshot_2

**Comment by astei** [comment]
> Currently there is always a compiler error because "Result" is not found among the imports of class

This sounds like a bug in the Java extension for Visual Studio Code. IntelliJ, Eclipse, and the Java compiler all resolve the import correctly.

> This is not a big change and will not break anything

I'm convinced but this is the wrong fix - the correct fix is to file a bug with the authors of the Java extension for Visual Studio Code.

**Comment by hugmanrique** [comment]
This is indeed a bug in the VS Code extension. Quoting [JLS 6.3](https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.3),
> The scope of a declaration of a member m declared in or inherited by a class type C ([§8.1.6](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1.6)) is the entire body of C, including any nested type declarations.

The `Result` interface is declared in the `ResultedEvent` interface, which `ServerLoginPluginMessageEvent` implements (and thus inherits, see [JLS 8.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.2)).

**Pull request merged**
