### PR TITLE
Added ServerPing.Builder#hoverMessage

### PR DESCRIPTION
**Pull request by 4drian3d**
Added a direct method to set a hover message in the ping response. This will make it easier to set a custom hover in the motd using formats like ~~legacy~~ or **MiniMessage**.

### CODE REVIEW

**Comment by kezz** [comment]
You shouldn't really be using the unusual hex code format - it is not part of the native legacy format, it was a hacky spigot addition. This should be downsampling the colours using the methods available on the builder (plus it should be being stored somewhere rather than being recreated in every single loop).

**Comment by hugmanrique** [comment]
This isn't the intended use of the sample players feature, and it can be recreated by a plugin using the current API, so I'm not sold on merging this.

**Comment by 4drian3d** [comment]
> This isn't the intended use of the sample players feature, and it can be recreated by a plugin using the current API, so I'm not sold on merging this.

I knew someone would say that, and yes, I know it's not a "proper" use and that at any time mojang could remove the legacy color codes, but I leave the pull request open in case someone has something else to say

**Comment by electronicboy** [comment]
I'm inclined to agree, I don't think that stuff relying on deprecated behavior which is already marked for removal should be part of the core API, this API would basically be deprecated on day 1 (but, this is on the list of stuff which needs to be consulted with mojang about potentially providing a more rich experience here, but 🤷 )

**Comment by astei** [comment]
Closing this PR. Unfortunately, what @electronicboy said is right: this is something Mojang is likely to deprecate and it would be better if there was a more rich, native experience here instead.

**Pull request closed without merging**
