### PR TITLE
Add Ukrainian localization

### PR DESCRIPTION
**Pull request by Black1ch**
Hello!
I made a translation of Velocity into Ukrainian and i ask you to add my translation.

Слава Україні!

### CODE REVIEW

**Comment by ArderMaxim** [comment]
I really need this!

Pls add

**Comment by hugmanrique** [comment]
Please see https://crowdin.com/project/velocity for submitting translations. In particular, Ukrainian isn't supported right now, but you can request the language addition in the Discord server (see the #velocity-translations channel).

**Comment by double-hope** [comment]
It's kinda quality translation and we really need this. 
Glory to Ukraine!

**Comment by Korg1X** [comment]
Add this pls its gonba be cool for ukrainian people. Thanks
Слава Україні

**Comment by Xernium** [comment]
Please see https://crowdin.com/project/velocity 
We added Ukranian the list. If there is anyone who wants to proofread the translation/has suggestions for changes please speak up on the papermc discord in the velocity-translations channel, thanks!

**Pull request closed without merging**
