### PR TITLE
Updated guice version to support Java 15

### PR DESCRIPTION
**Pull request by QuickGlare**
I've updated the version of Guice to support Java 15, I've done some tests and in my environment works fine.

### CODE REVIEW

**Comment by alexstaeding** [comment]
This is a breaking change that can't be included in velocity 1.x

**Comment by A248** [comment]
This will have to be re-targeted to Velocity 2.x, unfortunately.

**Comment by QuickGlare** [comment]
Ok, I've to close the pull request?

**Comment by zml2008** [comment]
Already been done on 2.x branch

**Comment by astei** [comment]
I'm going to be closing this as a API breakage is required to move to Guice 5 (and we've made the switch in the Velocity 2.0.0 development branch). In the meantime, there is already a viable workaround: use an older LTS version of Java.

**Pull request closed without merging**
