### PR TITLE
Update/chat order queue

### LINKED ISSUE #756: Chat order tracking
Internally, the proxy needs a queue to facilitate the order of chat-like packets sent to the server.

### PR DESCRIPTION
**Pull request by CoreyShupe**
Resolves #756 design open for discussion.

### CODE REVIEW

**Comment by CoreyShupe** [comment]
I think the whitespace changes are generally/mostly checkstyle re-formatting. Can remove it if necessary.

EDIT: Build failed, will fix the formatting? weird

**Comment by electronicboy** [comment]
rule 1 to life: don't fight with checkstyle, just accept it.

**Comment by Kapitowa** [comment]
Players sometimes can't send message.

**Comment by CoreyShupeSLG** [comment]
> Players sometimes can't send message.

can you provide more information - any error messages in the logs? Any error in chat? Are you running any plugins, etc...

**Comment by CoreyShupe** [comment]
Okay I see a potential bug which might cause that to happen - I will make a commit which should fix it for you.

**Comment by RhinoCD** [comment]
When will this fix be released?

**Comment by CoreyShupe** [comment]
> When will this fix be released?

uncertain if it will / if this design will even be accepted, don't know where this PR will go, I fixed the bug when chat sometimes wouldn't send

**Comment by RhinoCD** [comment]
humm, hope it gets fixed, having players just disconnect due to the bug is quite annoying. apparently doesn't kick them on other version tho

**Comment by CoreyShupe** [comment]
> humm, hope it gets fixed, having players just disconnect due to the bug is quite annoying. apparently doesn't kick them on other version tho

Does it kick them with this build?

**Comment by RhinoCD** [comment]
how do i test this build? is it in download tab if papermc

**Comment by CoreyShupe** [comment]
> how do i test this build? is it in download tab if papermc

You would need to build it from source. https://www.mediafire.com/file/p2fnrgtvwtlhcoe/velocity-proxy-3.1.2-SNAPSHOT-all.jar/file here's a download to the jar I built myself.

sha1 is 7c531e6a39cf6f80d73b18ab3708a91ca0d7d9f0

**Comment by RhinoCD** [comment]
error with the compiled jar, says it was compiled in a later java runtime or something

**Comment by lukemango** [comment]
> error with the compiled jar, says it was compiled in a later java runtime or something

use java 18

**Review by electronicboy — APPROVED** [review]

**Comment by astei** [comment]
@CoreyShupe can you update this for 1.19.1?

**Comment by CoreyShupe** [comment]
Ready to go :+1:

**Pull request merged**
