### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by limbo-app**

### CODE REVIEW

**Comment by robinhickmann** [comment]
@limbo-app, you just commited some swedish translations that I made but I also updated another text that was slightly inaccurate. velocity.command.glist-player-plural the singular and plural are the same in swedish so my update makes both texts the same like they should be.

**Comment by electronicboy** [comment]
it's a bot, pinging it has 0 effect, you'd need to see the crowdin

**Comment by robinhickmann** [comment]
oh mb, what do you mean by see the crowdin?

**Comment by electronicboy** [comment]
https://translate.papermc.io/velocity

**Comment by robinhickmann** [comment]
I don't know why you gave me that link, There are 2 translations that the bot didn't add, and my question now is if it will add them later or if theres anything I should do.

**Comment by electronicboy** [comment]
afaik it runs the task periodically, if it missed chances are it was just missed by the timing but, idk

**Review by kashike — APPROVED** [review]

**Pull request merged**
