### PR TITLE
Implement ComponentLogger

### PR DESCRIPTION
**Pull request by 4drian3d**
superseded by https://github.com/PaperMC/Velocity/pull/1022

### CODE REVIEW

**Comment by xIsm4** [comment]
> _ No description provided. _

Me guen the when, epic

**Comment by 4drian3d** [comment]
Tested, works correctly 
component-logger

**Comment by 4drian3d** [comment]
I have been trying for quite some time to implement a system similar to the one Paper has with a custom LogEventPatternConverter, but due to https://issues.apache.org/jira/browse/LOG4J2-673 it is impossible at the moment. Paper uses a non-"conventional" method to create its builds, so it is not affected

**Comment by electronicboy** [comment]
I can't look right now, but, iirc there is a transformer somewhere for
merging the plugin config things, in the past we used to just exclude that
file which sends l4j back to a class path scan

**Pull request closed without merging**
